{"name": "test_login_wrong_pws_manytime", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestLogin' object has no attribute 'driver'", "trace": "self = <tests.test_login.TestLogin object at 0x000001B3B86A65D0>\n\n    @pytest.fixture(autouse=True)\n    def classSetup(self):\n>       self.login_page = LoginPage(self.driver)\nE       AttributeError: 'TestLogin' object has no attribute 'driver'\n\ntests\\test_login.py:15: AttributeError"}, "description": "\n        System shows message when user enters wrong password many times.\n        :return:\n        ", "start": 1721017793718, "stop": 1721017793718, "uuid": "c347d475-31a9-4b57-ae74-9918bae9c0c8", "historyId": "4e96d6e7442c6f05e9317ee924afd076", "testCaseId": "4e96d6e7442c6f05e9317ee924afd076", "fullName": "tests.test_login.TestLogin#test_login_wrong_pws_manytime", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DUYEN"}, {"name": "thread", "value": "21876-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}