{"name": "test_login_wrong_pws_manytime", "status": "broken", "statusDetails": {"message": "AttributeError: 'TestLogin' object has no attribute 'driver'", "trace": "self = <tests.test_login.TestLogin object at 0x00000271F90A3C90>\n\n    @pytest.fixture(autouse=True)\n    def classSetup(self):\n>       self.login_page = LoginPage(self.driver)\nE       AttributeError: 'TestLogin' object has no attribute 'driver'\n\ntests\\test_login.py:16: AttributeError"}, "description": "\n        System shows message when user enters wrong password many times.\n        :return:\n        ", "start": 1721027653215, "stop": 1721027653215, "uuid": "6ccdc9c9-e05f-4894-9a77-1bef95e8c1a2", "historyId": "4e96d6e7442c6f05e9317ee924afd076", "testCaseId": "4e96d6e7442c6f05e9317ee924afd076", "fullName": "tests.test_login.TestLogin#test_login_wrong_pws_manytime", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DUYEN"}, {"name": "thread", "value": "25432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}